[project]
name = "deepseek"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bertviz>=1.4.1",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "torch>=2.7.1",
]
